### ISSUE TITLE
cimg/mysql image is significantly larger than mysql official image

### ISSUE THREAD

**Issue by matthewhively** [CircleCI-Public/cimg-mysql#16]
Compressed Size:
- 648MB ~ cimg/mysql:5.7
- 123MB ~ mysql:5.7

Is there a way to get the size reduced so it downloads faster? Or a `-slim` tag, or something like that?

**Comment by BytesGuy** [comment]
@matthewhively The main reason here is that the official mysql image is based on `debian:buster-slim` whereas our image is based on `cimg/base`

This is likely the main gain of the size reduction as in this particular image we already incorporate as many best practices as possible to ensure apt is cleaned etc. I have taken a look just now but cannot find anything that would allow us to save any significant space in the image over the base image.

I feel that this would be a better issue for `cimg/base`: https://github.com/CircleCI-Public/cimg-base

I will close this issue now, but please feel free to comment here if you need anything else, or open a PR if you have managed to find something that might help :)
