### ISSUE TITLE
Feature Request: Release image for mysql 8.0.33

### ISSUE THREAD

**Issue by olegpesok** [CircleCI-Public/cimg-mysql#20]
Is it possible to build a new version for mysql 8.0.33?

**Comment by olegpesok** [comment]
@ryanbourdais I don't think this was actually published to dockerhub unfortunately. It looks like `[release]` needs to be in the title of the commit message, not body for the script to work.

https://app.circleci.com/pipelines/github/CircleCI-Public/cimg-mysql/41/workflows/a10d9be2-5e31-4046-8190-86702e84b940/jobs/41

> Login Succeeded
Skipping publishing.

**Comment by ryanbourdais** [comment]
@olegpesok it seems I didn't squash and merge that PR so the commit message got changed like you pointed out, let me figure out the best way to proceed to fix this

**Comment by acorncom** [comment]
@ryanbourdais any updates here? It looks like there have been no updates to the 8.0.x series since 8.0.28 (https://hub.docker.com/r/circleci/mysql/tags?page=1&name=8.0.28)

**Comment by ryanbourdais** [comment]
Hi @acorncom sorry this took so long, there was issues with how the PRs were merged in not triggering a release for this image. It should all be fixed now and you should be able to run a build with 8.0.33

**Comment by acorncom** [comment]
@ryanbourdais appreciate it!
