### ISSUE TITLE
RAM versions of MySQL

### ISSUE THREAD

**Issue by TomK** [CircleCI-Public/cimg-mysql#7]
These "in-memory" mysql images have not been ported over to the new convenience images yet.

old:
https://github.com/CircleCI-Public/circleci-dockerfiles/blob/master/mysql/images/5.7.33/ram/Dockerfile

**Comment by ryanwohara** [comment]
https://github.com/CircleCI-Public/cimg-mysql#ram

**Comment by TomK** [comment]
On the old images the difference was significant.  I've since run some tests against the new image and they seem to be equivalent in run time to the old RAM image. Closing.
