### ISSUE TITLE
MySQL 5.6

### ISSUE THREAD

**Issue by nhattan** [CircleCI-Public/cimg-mysql#9]
Can you please upload MySQL 5.6? 
I know 5.7 is there but our application is currently using 5.6 which exists in the legacy circleci/mysql and it breaks if we upgrade to 5.7. 
Thanks

**Comment by felicianotech** [comment]
@BytesGuy I forget... did we not do this to begin with because it was old? Or because there was a compatibility issue with our Dockerfile?

**Comment by felicianotech** [comment]
Messaged him on Slack.

**Comment by BytesGuy** [comment]
This was a combination of the two. There were multiple incompatibilities with 5.6 and this version was EOL'd by Oracle  around February 2021. For now, I will close this issue as it is not something we are planning to do, but if we do get a significant number of requests for this then we can reconsider.
